# Generated by Django 4.0.3 on 2022-08-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('num_viviendas', models.IntegerField(max_length=4)),
                ('fecha_entrega', models.DateField()),
                ('dormitorios', models.IntegerField(max_length=4)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detalles', models.CharField(max_length=1000)),
                ('comercializa', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ventas', models.IntegerField(max_length=1)),
                ('proximas', models.IntegerField(max_length=1)),
                ('entregas', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titular', models.CharField(max_length=50)),
                ('texto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Imaganes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen1', models.ImageField(upload_to='archivos/')),
                ('imagen2', models.ImageField(upload_to='archivos/')),
                ('imagen3', models.ImageField(upload_to='archivos/')),
                ('imagen4', models.ImageField(upload_to='archivos/')),
                ('imagen5', models.ImageField(upload_to='archivos/')),
                ('imagen6', models.ImageField(upload_to='archivos/')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupoInmoApp.inmueble')),
            ],
        ),
    ]
