# Generated by Django 4.0.3 on 2022-08-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoInmoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imaganes',
            new_name='Imagene',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='subtitulo',
            field=models.CharField(default='inmueble', max_length=50),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='titulo',
            field=models.CharField(default='inmueble', max_length=50),
        ),
    ]
