# Generated by Django 4.0.3 on 2022-08-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoInmoApp', '0005_alter_inmueble_detalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagene',
            name='imagen1',
            field=models.ImageField(upload_to='grupoInmoApp/static/grupoInmoApp/archivos/'),
        ),
        migrations.AlterField(
            model_name='imagene',
            name='imagen2',
            field=models.ImageField(upload_to='archivos'),
        ),
        migrations.AlterField(
            model_name='imagene',
            name='imagen3',
            field=models.ImageField(upload_to='archivos'),
        ),
        migrations.AlterField(
            model_name='imagene',
            name='imagen4',
            field=models.ImageField(upload_to='archivos'),
        ),
        migrations.AlterField(
            model_name='imagene',
            name='imagen5',
            field=models.ImageField(upload_to='archivos'),
        ),
        migrations.AlterField(
            model_name='imagene',
            name='imagen6',
            field=models.ImageField(upload_to='archivos'),
        ),
    ]
