# Generated by Django 4.0.3 on 2022-08-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoInmoApp', '0008_alter_imagene_imagen1_alter_imagene_imagen2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagene',
            name='imagen1',
            field=models.ImageField(upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='imagene',
            name='imagen2',
            field=models.ImageField(upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='imagene',
            name='imagen3',
            field=models.ImageField(upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='imagene',
            name='imagen4',
            field=models.ImageField(upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='imagene',
            name='imagen5',
            field=models.ImageField(upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='imagene',
            name='imagen6',
            field=models.ImageField(upload_to='imagenes'),
        ),
    ]
