# Generated by Django 4.0.3 on 2022-08-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoInmoApp', '0010_inmueble_portada_noticia_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='fecha_entrega',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.CharField(default='', max_length=20),
        ),
    ]
