# Generated by Django 4.0.3 on 2022-08-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoInmoApp', '0011_alter_inmueble_fecha_entrega_alter_inmueble_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='detalles',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='dormitorios',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='entregas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='proximas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='superficie',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='ventas',
            field=models.BooleanField(default=False),
        ),
    ]
