# Generated by Django 4.0.3 on 2022-09-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoInmoApp', '0012_alter_inmueble_detalles_alter_inmueble_dormitorios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo1', models.FileField(upload_to='detalles-archivos')),
                ('archivo2', models.FileField(upload_to='detalles-archivos')),
                ('archivo3', models.FileField(upload_to='detalles-archivos')),
                ('archivo4', models.FileField(upload_to='detalles-archivos')),
                ('archivo5', models.FileField(upload_to='detalles-archivos')),
            ],
        ),
    ]
