# Generated by Django 4.0.3 on 2022-09-13 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupoInmoApp', '0013_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='inmueble',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='grupoInmoApp.inmueble'),
        ),
    ]
