# Generated by Django 4.0.3 on 2022-09-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoInmoApp', '0015_remove_noticia_titular_noticia_subtitulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
