# Generated by Django 4.0.3 on 2022-09-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoInmoApp', '0017_alter_noticia_subtitulo_alter_noticia_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='bibliografia',
            field=models.URLField(blank=True, null=True),
        ),
    ]
