# Generated by Django 4.1.1 on 2022-11-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupoInmoApp', '0018_noticia_bibliografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='correo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='telefono',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo1',
            field=models.FileField(blank=True, null=True, upload_to='detalles-archivos'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo2',
            field=models.FileField(blank=True, null=True, upload_to='detalles-archivos'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo3',
            field=models.FileField(blank=True, null=True, upload_to='detalles-archivos'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo4',
            field=models.FileField(blank=True, null=True, upload_to='detalles-archivos'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo5',
            field=models.FileField(blank=True, null=True, upload_to='detalles-archivos'),
        ),
    ]
